trigger: none

variables:
  - group: packer-image-build-variables
  - template: infra-pipeline-variables.yml

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Init
    displayName: Init
    jobs:
      - job: Init_start
        steps:
          - task: TerraformInstaller@0
            displayName: "Install Terraform latest"

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - init"
            inputs:
              backendServiceArm: "packer-service-connection"
              backendAzureRmResourceGroupName: ${{variables.devops_rg}}
              backendAzureRmStorageAccountName: ${{variables.devops_storage}}
              backendAzureRmContainerName: ${{variables.devops_storage_container}}
              backendAzureRmKey: ${{variables.tfstatefile}}

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - validate"
            inputs:
              command: validate

  - stage: Plan
    dependsOn: Init
    condition: succeeded('Init')
    jobs:
      - job: Plan_job
        steps:
          - task: TerraformInstaller@0
            displayName: "Install Terraform latest"

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - init"
            inputs:
              backendServiceArm: "packer-service-connection"
              backendAzureRmResourceGroupName: ${{variables.devops_rg}}
              backendAzureRmStorageAccountName: ${{variables.devops_storage}}
              backendAzureRmContainerName: ${{variables.devops_storage_container}}
              backendAzureRmKey: ${{variables.tfstatefile}}

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - plan"
            inputs:
              command: plan
              environmentServiceNameAzureRM: "packer-service-connection"
              backendServiceArm: "packer-service-connection"

  - stage: apply
    dependsOn: Plan
    condition: succeeded('Plan')
    jobs:
      - job: apply_job
        steps:
          - task: TerraformInstaller@0
            displayName: "Install Terraform latest"

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - init"
            inputs:
              backendServiceArm: "packer-service-connection"
              backendAzureRmResourceGroupName: ${{variables.devops_rg}}
              backendAzureRmStorageAccountName: ${{variables.devops_storage}}
              backendAzureRmContainerName: ${{variables.devops_storage_container}}
              backendAzureRmKey: ${{variables.tfstatefile}}

          - task: TerraformTaskV2@2
            displayName: "Terraform : azurerm - apply"
            inputs:
              command: apply
              commandOptions: "-auto-approve"
              environmentServiceNameAzureRM: "packer-service-connection"
