trigger: none

variables:
  - template: infra-pipeline-variables.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: "Install Terraform latest"

  - task: TerraformTaskV2@2
    displayName: "Terraform : azurerm - init"
    inputs:
      backendServiceArm: "packer-service-connection"
      backendAzureRmResourceGroupName: ${{variables.devops_rg}}
      backendAzureRmStorageAccountName: ${{variables.devops_storage}}
      backendAzureRmContainerName: ${{variables.devops_storage_container}}
      backendAzureRmKey: ${{variables.tfstate}}

  - task: TerraformTaskV2@2
    displayName: "Terraform : azurerm - destroy"
    inputs:
      command: destroy
      environmentServiceNameAzureRM: "packer-service-connection"
